// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SEIIApp.Server.Data;

namespace SEIIApp.Server.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    partial class ApplicationDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.6");

            modelBuilder.Entity("SEIIApp.Server.Domain.LessonDefinition", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("lessonNumber")
                        .HasColumnType("int");

                    b.Property<string>("lessonTitle")
                        .HasColumnType("longtext");

                    b.Property<string>("text")
                        .HasColumnType("longtext");

                    b.Property<string>("videoUrl")
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.HasIndex("lessonNumber")
                        .IsUnique();

                    b.ToTable("LessonDefinitions");
                });

            modelBuilder.Entity("SEIIApp.Server.Domain.LessonProfilDefinition", b =>
                {
                    b.Property<int>("lessonProfilId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("lessonNumber")
                        .HasColumnType("int");

                    b.HasKey("lessonProfilId");

                    b.HasIndex("lessonNumber");

                    b.HasIndex("Id", "lessonNumber")
                        .IsUnique();

                    b.ToTable("LessonProfilDefinitions");
                });

            modelBuilder.Entity("SEIIApp.Server.Domain.MessageDefinition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("receiverId")
                        .HasColumnType("int");

                    b.Property<string>("receiverName")
                        .HasColumnType("longtext");

                    b.Property<int>("senderId")
                        .HasColumnType("int");

                    b.Property<string>("senderName")
                        .HasColumnType("longtext");

                    b.Property<string>("text")
                        .HasColumnType("longtext");

                    b.Property<bool>("unread")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.ToTable("MessageDefinitions");
                });

            modelBuilder.Entity("SEIIApp.Server.Domain.ProfilDefinition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateProfile")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("FirstName")
                        .HasColumnType("longtext");

                    b.Property<string>("LastName")
                        .HasColumnType("longtext");

                    b.Property<string>("Passwort")
                        .HasColumnType("longtext");

                    b.Property<string>("UrlImage")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("ProfilDefinitions");
                });

            modelBuilder.Entity("SEIIApp.Server.Domain.LessonProfilDefinition", b =>
                {
                    b.HasOne("SEIIApp.Server.Domain.ProfilDefinition", "ProfilDefinition")
                        .WithMany("LessonProfilDefinition")
                        .HasForeignKey("Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SEIIApp.Server.Domain.LessonDefinition", "LessonDefinition")
                        .WithMany("LessonProfilDefinition")
                        .HasForeignKey("lessonNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LessonDefinition");

                    b.Navigation("ProfilDefinition");
                });

            modelBuilder.Entity("SEIIApp.Server.Domain.LessonDefinition", b =>
                {
                    b.Navigation("LessonProfilDefinition");
                });

            modelBuilder.Entity("SEIIApp.Server.Domain.ProfilDefinition", b =>
                {
                    b.Navigation("LessonProfilDefinition");
                });
#pragma warning restore 612, 618
        }
    }
}
